config/routes.rb
Rails.application.routes.draw do

  root "votaciones#listar"
  post "votaciones/:id_restaurante/puntaje/:id_puntaje", to: "votaciones#votar", as: 'votar_restaurante'
  
  #Rutas Tipos Comidas
  get     'tipos_comidas',            to: 'tipos_comidas#listar',   as: 'tipos_comidas'       #listar
  get     'tipos_comidas/nuevo',      to: 'tipos_comidas#crear',    as: 'nuevo_tipo_comida'   #formulario de nuevo
  get     'tipos_comidas/:id',        to: 'tipos_comidas#mostrar',  as: 'tipo_comida'         #vista del detalle de un tipo de comida
  get     'tipos_comidas/:id/editar', to: 'tipos_comidas#editar',   as: 'editar_tipo_comida'  #formulario para editar el registro

  post    'tipos_comidas',            to: 'tipos_comidas#guardar'
  put     'tipos_comidas/:id',        to: 'tipos_comidas#actualizar'
  patch   'tipos_comidas/:id',        to: 'tipos_comidas#actualizar'
  delete  'tipos_comidas/:id',        to: 'tipos_comidas#eliminar'

  # Rutas Puntajes
  get     'puntajes',                 to: 'puntajes#listar',        as: 'puntajes'
  get     'puntajes/nuevo',           to: 'puntajes#crear',         as: 'nuevo_puntaje'
  get     'puntajes/:id',             to: 'puntajes#mostrar',       as: 'puntaje'
  get     'puntajes/:id/editar',      to: 'puntajes#editar',        as: 'editar_puntaje'

  post    'puntajes',                 to: 'puntajes#guardar'
  put     'puntajes/:id',             to: 'puntajes#actualizar'
  patch   'puntajes/:id',             to: 'puntajes#actualizar'
  delete  'puntajes/:id',             to: 'puntajes#eliminar'

  # Usuarios
  get     'usuarios',                 to: 'usuarios#listar',        as: 'usuarios'
  get     'usuarios/nuevo',           to: 'usuarios#crear',         as: 'nuevo_usuario'
  get     'usuarios/:id',             to: 'usuarios#mostrar',       as: 'usuario'
  get     'usuarios/:id/editar',      to: 'usuarios#editar',        as: 'editar_usuario'
  
  post    'usuarios',                 to: 'usuarios#guardar'     
  put     'usuarios/:id',             to: 'usuarios#actualizar'    #buena práctica colocar el PUT
  patch   'usuarios/:id',             to: 'usuarios#actualizar'   
  delete  'usuarios/:id',             to: 'usuarios#eliminar'     

  #Restaurantes
  get     'restaurantes',             to: 'restaurantes#listar',    as: 'restaurantes' 
  get     'restaurantes/nuevo',       to: 'restaurantes#crear',     as: 'nuevo_restaurante'
  get     'restaurantes/:id',         to: 'restaurantes#mostrar',   as: 'restaurante'      
  get     'restaurantes/:id/editar',  to: 'restaurantes#editar',    as: 'editar_restaurante'
  
  post    'restaurantes',             to: 'restaurantes#guardar'
  put     'restaurantes/:id',         to: 'restaurantes#actualizar'       
  patch   'restaurantes/:id',         to: 'restaurantes#actualizar'
  delete  'restaurantes/:id',         to: 'restaurantes#eliminar'

  #Rutas Platos
  get   'platos',                   to: 'platos#listar',          as: 'platos'    
  get   'platos/nuevo',             to: 'platos#crear',           as: 'nuevo_plato' 
  get   'platos/:id',               to: 'platos#mostrar',         as: 'plato'
  get   'platos/:id/editar',        to: 'platos#editar',          as: 'editar_plato'

  post   'platos',                  to: 'platos#guardar'
  put    'platos/:id',              to: 'platos#actualizar'
  patch  'platos/:id',              to: 'platos#actualizar'
  delete 'platos/:id',              to: 'platos#eliminar'
  
  #Rutas Promociones
  # get    'promociones',             to: 'promociones#listar',    as: 'promociones'     
  # get    'promociones/nuevo',       to: 'promociones#crear',     as: 'nuevo_promocion'     
  # get    'promociones/:id',         to: 'promociones#mostrar',   as: 'promocion'     
  # get    'promociones/:id/editar',  to: 'promociones#editar',    as: 'editar_promocion'     

  # post   'promociones',             to: 'promociones#guardar'
  # put    'promociones/:id',         to: 'promociones#actualizar'
  # patch  'promociones/:id',         to: 'promociones#actualizar'
  # delete 'promociones/:id',         to: 'promociones#eliminar'

  #Rutas Invitaciones
  #get     'invitaciones',            to: 'invitaciones#listar',   as: 'invitaciones'
  #get     'invitaciones/nuevo',      to: 'invitaciones#crear',    as: 'nuevo_invitacion'
  #get     'invitaciones/:id',        to: 'invitaciones#mostrar',  as: 'invitacion'
  #get     'invitaciones/:id/editar', to: 'invitaciones#editar',   as: 'editar_invitacion'

  # post   'invitaciones',            to: 'invitaciones#guardar'
  # put    'invitaciones/:id',        to: 'invitaciones#actualizar'
  # patch  'invitaciones/:id',        to: 'invitaciones#actualizar'
  # delete 'invitaciones/:id',        to: 'invitaciones#eliminar'
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
  belongs_to :tipo_comida   # esto va en singular
  has_many :platos

  has_many :invitaciones
  #has_many :usuarios, through: :invitaciones

  has_many :promociones
  #has_many :usuarios, through: :promociones

  has_many :puntajes
  #has_many :puntajes, through: :puntajes_restaurantes

  validates(:nombre, presence: true, uniqueness: true)
  validates(:tipo_comida_id, presence: true)

end

app/controllers/restaurantes_controller.rb
#Controladores son en plural
class RestaurantesController < ApplicationController

    before_action :asignar_restaurante, only: [:editar, :mostrar, :actualizar, :eliminar]
    #GET / restaurantes
    def listar
        @restaurantes = Restaurante.all
    end

    #GET /restaurantes/nuevo
    def crear
        @restaurante = Restaurante.new
        @tipos_comidas = TipoComida.all
    end

    #GET /restaurantes/editar
    def editar
        @tipos_comidas = TipoComida.all
    end

    #GET /restaurantes/:id
    def mostrar

    end

    #POST /restaurantes
    def guardar
        @restaurante = Restaurante.new(params_restaurante)
        if @restaurante.save
            redirect_to restaurantes_path #TODO crear la ruta
        else
            @tipos_comidas = TipoComida.all
            render :crear
        end
    end

    #GET /restaurantes/editar
    def actualizar
        @restaurante.nombre = params_restaurante[:nombre]
        @restaurante.tipo_comida_id = params_restaurante[:tipo_comida_id]
        if @restaurante.save
            redirect_to restaurantes_path
        else
            @tipos_comidas = TipoComida.all
            render :editar
        end
    end

    def eliminar
        @restaurante.destroy
        redirect_to restaurantes_path
    end

    private

    def asignar_restaurante
        @restaurante = Restaurante.find(params[:id])
    end

    def params_restaurante
        datos_restaurantes = params.require(:restaurante).permit(:nombre, :tipo_comida_id)
    end
end

app/views/restaurantes/_formulario.html.erb
<%= form_with(model: base_restaurante) do |formulario| %>

    <div class="mb-3">
        <%= formulario.label :nombre, class: 'form-label' %>
        <%= formulario.text_field :nombre, class: 'form-control' %>
        <% if base_restaurante.errors[:nombre].any? %>
            <div class="alert alert-danger" role="alert">
                <%= base_restaurante.errors[:nombre].first %>
            </div>
        <% end %>
    </div>
    <div class="mb-3">
        <%= formulario.label :tipo_comida_id, class: 'form-label' %>
        <%= formulario.select :tipo_comida_id, 
            options_from_collection_for_select(base_tipos_comidas, :id, :tipo, base_restaurante.tipo_comida_id),
            { include_blank: 'Elige un tipo de comida' },
            class: "form-select" %>
        <% if base_restaurante.errors[:tipo_comida_id].any? %>
            <div class="alert alert-danger" role="alert">
                <%= base_restaurante.errors[:tipo_comida_id].first %>
            </div>
        <% end %>
    </div>

    <%= formulario.submit %>

<% end %>

app/views/restaurantes/crear.html.erb
<h1>Registrar nuevo restaurante</h1>

<%= render "formulario", base_restaurante: @restaurante, base_tipos_comidas: @tipos_comidas %>

app/views/restaurantes/editar.html.erb
<h1>Editar restaurante</h1>

<%= render "formulario", base_restaurante: @restaurante, base_tipos_comidas: @tipos_comidas %>

app/views/restaurantes/listar.html.erb
<h1>Lista de restaurantes</h1>

<%= link_to "Nuevo restaurante", nuevo_restaurante_path %>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Tipo de comida</th>
        <th>Acciones</th>
    </tr>

    <% @restaurantes.each do |restaurante| %>
        <tr>
            <td><%= restaurante.id %></td>
            <td><%= link_to restaurante.nombre, restaurante_path(restaurante) %></td>
            <td><%= restaurante.tipo_comida.tipo %></td>
            <td>
                <%= link_to "editar", editar_restaurante_path(restaurante) %>
                <%= link_to "eliminar", restaurante_path(restaurante), method: :delete, data: { confirm: "¿está seguro que quiere eliminar el restaurante?" } %>
            </td> 
        </tr>
    <% end %>
</table>

app/views/restaurantes/mostrar.html.erb
<h1>Datos del restaurante</h1>

<%= @restaurante.id%>
<%= @restaurante.nombre%>
<%= @restaurante.tipo_comida.tipo%>

<%= link_to "volver", restaurante_path %>